module.exports = [
    ["Habari Nyepesi Nyepesi", "Ngwengwe", "Bangi", "Zali la mentali", "Google"],
    ["Kalumanzila", "Mtanashati", "Kidumu", "P.I.M.P.", "Olduvai Gorge"],
    ["Mzungu wa nne", "Radio Mbao", "JK", "Shamba Dress", "Msimbazi"],
    ["Mzazi mwenzangu", "Bluetooth", "Bongo bahati mbaya", "Sadakalawe", "Papa Wemba"],
    ["Peremende", "Samba Mapangala", "Boshori", "Sister P", "Albino"],
    ["Stay Liquid", "Kisiki cha mpingo", "Posa", "Weweseka", "Angali Mbichi"],
    ["Salaale", "Makande", "Kuti Kavu", "Niajiri", "Hadji Manara"],
    ["Babu Tale", "Pwani", "Kinyarwanda", "Alfu lela ulela", "Habari ndo hiyo"],
    ["Frozen", "Kifimbo Cheza", "Kachumbari", "Cinderella", "Mwanzo Mgumu "],
    ["Mambo Mseto", "Kizungumkuti", "Daladala", "Y2K", "Mshereheshaji"],
    ["Kilaza", "John Doe ", "Pilau", "Twanga Pepeta ", "Umbo Namba 8"],
    ["Edward Lowassa", "Ba Mdogo", "Haramu", "Muhogo Mchungu", "Jokofu"],
    ["Zafanana", "Sechelela", "JPM", "Mr. Ebo", "This is simba"],
    ["Mahabusu", "Mr. Countdown ", "Tatu Bila ", "Mbagala Rangi Tatu", "Mvua ya mawe"],
    ["Hindumandal", "Nokia Ya Tochi", "Bombadia", "Mapenzi Mubashara", "Kodi ya pango"],
    ["Kayumba", "Nyambizi", "Mchikichini", "Pasua Kichwa", "Mchepuko"],
    ["Kibonde", "Magogoni", "Kamwene", "Kigori", "Topetope"],
    ["Mama Huruma", "Cha Arusha", "Mtani", "Mbayuwayu", "Buku Jero"],
    ["Mchungwa", "Mgaagaa na upwa", "Kudamshi", "Serengeti Boy", "Zakayo"],
    ["Sweet Menthol", "Mwanaume Suruali", "Mbarabaigi", "Beberu", "Africa Unite"],
    ["Hakuna Matata", "Raba Mtoni", "Bi Mkora", "Ki Ben 10", "Vyuma Vimekaza"],
    ["Bishosti", "Chausiku", "Titanic", "Form Six", "Mange Kimambi"],
    ["Singeli", "Gololi", "Pundamilia", "Za saa hizi", "Njugu Mawe"],
    ["Pantoni", "Chapati Mbili", "Komando Kipensi", "Wali Mkavu", "Zege"],
    ["Dar Mpaka Moro", "Konda", "Lady Gaga", "Mwabepande", "Segera"]
]